NeuralNetworkVerification/Marabou

- src/engine/DnCManager.cpp
- src/engine/Marabou.cpp
This PR removes the rounding when printing the model
> do not perform rounding when printing models

- src/input_parsers/PropertyParser.cpp
- src/input_parsers/PropertyParser.h
This PR introduces:
* a check that right handside of each constraint is a scalar
* minor changes in the property parser
> Property parser scalar check

- maraboupy/examples/Example Notebook.ipynb
[issue 174](https://github.com/guykatzz/Marabou/issues/174)
@tomerarnon
> Make example run with no errors

- src/common/MString.h
- src/common/Vector.h
- src/engine/DnCManager.cpp
> Fix issue 215

- src/engine/Engine.cpp
Right now, we only perform SBT on the first branch of a PL constraint. This PR address that.
Comparison on ACAS benchmarks using DnC mode (8 core)
SBT on both branches solves 1 more SAT, 5 more UNSAT than the current version.
> perform sbt on both branches

- src/common/FloatUtils.h
Improvement of 0.5-1% (in cpu) on properties 1-4 (acas)
More detailed summary:
DIRECTORY | Tot | Slvd | Sat | Unsat |  To |    Cpu[s] |  Mem[MB] |
optimize-iszero-20200420-p1 |  45 |   11 |   0 |    11 |  34 |  138758.3 |  36072.6
master-20200420-p1 |  45 |   11 |   0 |    11 |  34 |  138887.3 |  36083.7
optimize-iszero-20200420-p2 |  45 |   33 |  33 |     0 |  12 |  60747.7 |  31354.7
master-20200420-p2 |  45 |   33 |  33 |     0 |  12 |  61105.1 |  31356.8
optimize-iszero-20200420-p3 |  45 |   43 |   3 |    40 |   2 |  21733.5 |  13147.7
master-20200420-p3 |  45 |   43 |   3 |    40 |   2 |  22060.8 |  13137.9
optimize-iszero-20200420-p4 |  45 |   45 |   3 |    42 |   0 |  8955.9 |  12424.3
master-20200420-p4 |  45 |   45 |   3 |    42 |   0 |  9112.5 |  12426.3 
Thanks to @ahmed-irfan …
> Optimize iszero

- src/common/Statistics.cpp
A single line change - added SBT time to getTotalTime() so it gets accounted for when deciding whether to timeout or not.
> Added SBT time to getTotalTime() so it gets accounted for when deciding whether to timeout or not

- .gitignore
- CMakeLists.txt
- tools/download_openBLAS.sh
* rename OpenBLAS script to match schema 
* add downloaded files to gitignore
* do quiet wget
> remove openblas artifacts

- maraboupy/Marabou.py
- maraboupy/MarabouCore.cpp
- maraboupy/MarabouNetwork.py
- maraboupy/MarabouNetworkNNet.py
- maraboupy/MarabouNetworkONNX.py
- maraboupy/MarabouNetworkTF.py
- maraboupy/MarabouUtils.py
This pr edits all of the docstrings for Maraboupy classes and functions in preparation for automatic documentation generation.
Most edits just reformat existing docstrings, but some were added, such as for Marabou.createOptions and MarabouCore.cpp. 
A subsequent pr will add the code necessary to make html pages generated by these docstrings.
> Maraboupy docstrings in Google syntax

- src/common/GurobiWrapper.cpp
- src/common/GurobiWrapper.h
- src/configuration/GlobalConfiguration.cpp
- src/configuration/GlobalConfiguration.h
- src/nlr/LPFormulator.cpp
- src/nlr/LPFormulator.h
Let LPFormulator own a GurobiWrapper, which can be reuse.
> Reuse GurobiWrapper in LPFormulator

- src/engine/MaxConstraint.cpp
- src/engine/MaxConstraint.h
Signed-off-by: tagomaru <tagomaru@users.noreply.github.com>
This PR is going to resolve #367 .
> Fix the bug of unregisterAsWatcher

- maraboupy/MarabouCore.cpp
- maraboupy/MarabouNetwork.py
- maraboupy/MarabouNetworkONNX.py
- maraboupy/MarabouNetworkTF.py
- maraboupy/examples/5_DisjunctionConstraintExample.py
- maraboupy/test/test_network.py
- maraboupy/test/test_tf.py
- src/common/CommonError.h
- src/engine/InputQuery.cpp
Allow users to add disjunction constraints through the Python API
> Expose disjunction constraint to Python API

- src/engine/tests/Test_MILPEncoder.h
- src/nlr/MILPFormulator.cpp
Fix memory leaks in Tests for encoding max constraints as MILP.
> Milp memory leak

- README.md
This PR updates the README.md with:
- Updated information about Windows support
- Adds CI badge
- Moves CI and CodeCov badges in line with the heading
- Add a link to NeuralNetworkVerification.github.io
> Update README.md - Windows support, CI badge, link to research

- src/configuration/OptionParser.cpp
- src/configuration/Options.cpp
This PR is going to change the number of simulation from 1 to 100 based on an experiment.
> Change the number of simulation

- maraboupy/MarabouNetwork.py
Saving us the pain on doing it ourselves..
> support pathlib paths

- src/engine/CostFunctionManager.cpp
- src/engine/CostFunctionManager.h
- src/engine/Engine.cpp
- src/engine/Engine.h
- src/engine/ICostFunctionManager.h
- src/engine/ITableau.h
- src/engine/Tableau.cpp
- src/engine/tests/MockCostFunctionManager.h
- src/engine/tests/Test_CostFunctionManager.h
- src/engine/tests/Test_Tableau.h
- src/system_tests/Test_lp.h
1. Extend the Tableau and CostFunctionManager to handle optimization.
2. Add a minimizeHeuristicCost() method to the Engine class.
> Add optimization method in the Engine class

- src/engine/AbsoluteValueConstraint.cpp
- src/engine/Engine.cpp
- src/engine/MaxConstraint.cpp
- src/engine/ReluConstraint.cpp
- src/engine/SignConstraint.cpp
Toggle the optimization flag to false when exceptions are thrown.
Remove the assertions in getSoICostComponents.
> Toggle optimisation flag and remove SoI assertions.

- maraboupy/MarabouNetworkONNX.py
Generalize batch norm to high dimension inputs.
> Update onnx batch norm parser  

- src/input_parsers/OnnxParser.cpp
Hopefully self-explanatory given code documentation.
> Fix bug when parsing unknown dimension sizes in `OnnxParser.cpp`

- THANKS
Matthew has had several PRs merged, but isn’t listed in THANKS.
This PR adds him.
> Add Matthew Daggitt to THANKS

- maraboupy/MarabouNetworkONNX.py
- maraboupy/test/test_onnx.py
Add a function in the MarabouNetworkONNX class to split a onnx file at a node to create two sub-onnx files.
> Add function to split a onnx network

- CHANGELOG.md
- src/input_parsers/NetworkParser.cpp
Okay these bugs are little embarrassing on my part. Apologies for introducing them...
> Fixed bugs with Sigmoid layers in C++ ONNX parser

- src/input_parsers/NetworkParser.cpp
- src/input_parsers/NetworkParser.h
- src/input_parsers/OnnxParser.cpp
> Moved generic constraints from OnnxParser to NetworkParser

- src/engine/DnCMarabou.cpp
- src/engine/Marabou.cpp
- src/input_parsers/InputQueryBuilder.cpp
- src/input_parsers/InputQueryBuilder.h
- src/input_parsers/OnnxParser.cpp
- src/input_parsers/OnnxParser.h
- src/input_parsers/tests/Test_OnnxParser.h
- src/input_parsers/tests/Test_VnnLibParser.h
Now matches the corresponding Python files almost perfectly.
> Refactor C++ ONNXParser to a pure style that takes in an InputQueryBuilder as an argument.

- CHANGELOG.md
- src/common/GurobiWrapper.cpp
- src/common/GurobiWrapper.h
- src/configuration/GlobalConfiguration.cpp
- src/configuration/GlobalConfiguration.h
- src/configuration/OptionParser.cpp
- src/configuration/Options.cpp
- src/engine/Engine.cpp
- src/engine/Engine.h
- src/engine/MILPSolverBoundTighteningType.h
- src/input_parsers/OnnxParser.cpp
- src/nlr/LPFormulator.cpp
- src/nlr/LPFormulator.h
- src/nlr/Layer.cpp
- src/nlr/Layer.h
- src/nlr/MILPFormulator.cpp
- src/nlr/NetworkLevelReasoner.cpp
- src/nlr/NetworkLevelReasoner.h
- src/nlr/tests/Test_NetworkLevelReasoner.h
- Introduces an additional mode to perform backward LP-tightening as described in https://arxiv.org/abs/2203.03153 
- Also fix #730
> Backward analysis

- .gitignore
- CMakeLists.txt
- pyproject.toml
- tools/download_boost.sh
- tools/download_onnx.sh
- tools/download_openBLAS.sh
- tools/download_protobuf.sh
- tools/download_pybind11.sh
Versions are all set once in the CMakeLists file
> Refactor CMakeList and download scripts to use versions from a single source

- .github/workflows/cibuildwheel.yml
- pyproject.toml
Will create a PR to bump the version to 2.0 after this is merged.
> bump  supported python versions in pyproject.toml

- src/engine/Engine.cpp
- src/engine/IQuery.h
- src/engine/InputQuery.cpp
- src/engine/Query.cpp
- src/engine/Query.h
Use tightenbound instead of setBound in the extract bound methods. Otherwise, calculateBound does not work with incremental solving.
> use tightenBound in extractBound
