NeuralNetworkVerification/Marabou

maraboupy/MarabouNetwork.py, maraboupy/MarabouNetworkTF.py, src/engine/Engine.cpp
This is really two very simple PRs merged into one, so I can split this up if needed.
There's a place in Engine.cpp that doesn't  check _verbosity before printing, which is fixed here. 
Also, maraboupy's function for evaluating a network at a point always prints a line that is not useful because it just tells the user that they called the function. When evaluating many points with maraboupy, this can result in a lot of print statements, so I think it's best to remove the print statement.
=> Minor fix for printing

Rules.mk, src/engine/main.cpp
This PR adds the built details to the version option flag.
Here is how the output looks like:
```
./src/engine/marabou.elf --version
Marabou version 1.0.+ [branch-name b42baa8677a054dbaded5c56c9ecf6d0bc1d2b0a]
compiled with GCC version 8.3.0
on Aug 29 2019 14:26:29
```
=> Build details with the version option

src/common/Debug.h, src/common/File.cpp, src/common/MString.cpp, src/common/Vector.h, src/common/tests/Test_FloatUtils.h, src/common/tests/Test_Vector.h, src/engine/DnCManager.cpp, src/input_parsers/AcasNeuralNetwork.cpp, src/input_parsers/PropertyParser.cpp
This is the first of two pull requests so that Marabou can be compiled on a Windows machine using Visual Studio. This PR contains changes to files that affect compilation on all machines, whereas the other PR will only contain changes that affect compilation on a Windows machine.
There are four types of changes:
1. Adding a comma before "..." in macro argument list
2. Removing instances where arrays are initialized with variable length
3. Changing the divide-by-zero test to use a variable instead of hard-coded zero
4. "xor" to "^"
These are all small changes needed to compile on Windows with Visual Studio but are not Windows specific. I'm able to run tests and maraboupy successfully on my Linux machine with these changes added.
=> Changes for Windows that also affect Linux

maraboupy/MarabouCore.cpp, maraboupy/MarabouNetwork.py
Apparently these two PRs (https://github.com/guykatzz/Marabou/pull/198, https://github.com/guykatzz/Marabou/pull/195) which were both opened at one time added the same functionality to the python API that marks the input and output variables. So I'm removing this redundancy.
=> Patch to dnc python api

CMakeLists.txt, README.md, maraboupy/tests.py
Add option to choose between python 2 and 3 (where default is 3)
If only one python version is installed will choose that, if both are installed will use the default.
Other then that fixed the tests.py example (after introducing MarabouOptions) which broke it....
=> Choose python version

src/engine/Tableau.cpp
When adding an equation to the tableau, if the scalar of the equation isn't zero. hence `b[m-1]`, we should set the indicator `_rhsIsAllZeros` to false.
=> Fix to initialize `_rhsIsAllZeros` in case `b` isn't zero when adding an Equation

src/configuration/GlobalConfiguration.cpp, src/configuration/GlobalConfiguration.h, src/engine/Engine.cpp, src/engine/Engine.h, src/engine/PiecewiseLinearConstraint.h, src/engine/ReluConstraint.cpp, src/engine/ReluConstraint.h, src/engine/tests/Test_ReluConstraint.h
Add method to compute the polarity of a Relu and bias the fixing and case split order based on it.
Tested on 60 acas benchmarks and 40 MNIST benchmarks. 
Solved 11 more SAT and 3 more UNSAT with a 20 minutes timeout compared to the current master.
=> Polarity based direction heuristics

src/configuration/OptionParser.cpp, src/configuration/Options.cpp, src/configuration/Options.h, src/engine/DnCManager.cpp, src/engine/DnCManager.h, src/engine/DnCMarabou.cpp, src/engine/Engine.cpp, src/engine/Engine.h, src/engine/Marabou.cpp, src/engine/SmtCore.cpp, src/engine/SmtCore.h
Give users the ability to change the constraint violation threshold.
Usage:
`./Marabou [network] [property] --split-threshold=1`
On ACAS benchmarks (property 1-4) with a 30 minutes timeout, 
split-threshold=1 solves 9 more SAT and 5 more UNSAT than split-threshold=20.
=> Add Constraint Violation Threshold as an command line option

CMakeLists.txt, README.md, src/common/Debug.h
=> Use ndebug

CMakeLists.txt, src/engine/ReluConstraint.cpp, src/engine/tests/Test_ReluConstraint.h
In a ReLU's active split, if we already have an auxiliary variable aux = f - b, we don't add a new equation; instead, we make aux strictly 0.
=> Improved Relu splits

maraboupy/MarabouNetworkONNX.py
Torch converts Flatten-like operations to ONNX.Flatten, even if `.reshape()` is explicitly used. This pull request should add support for ONNX.Flatten. It is based on the implementation for ONNX.Reshape.
=> ONNX Flatten support

maraboupy/MarabouCore.cpp
When DnC is used through the Python API and times out, a freshly constructed Statistics object is returned. This is problematic as retStats.hasTimedOut() needs to be True. This short PR fixes this bug.
=> Fix bug related to DnC return value

src/engine/DnCManager.cpp, src/engine/DnCManager.h
Currently in DnC, inputQuery is preprocessed multiple times. 
This PR preprocess the inputQuery once with the baseEngine in DnCManager, and the worker engines only copy over the preprocessed input query.
=> Preprocess the input query only once in DnC

src/configuration/GlobalConfiguration.cpp, src/configuration/GlobalConfiguration.h, src/engine/Preprocessor.cpp, src/engine/Preprocessor.h
- Create a log function in the Preprocessor class.
- Move the print statements to logger in the Preprocessor::preprocess method.
=> move print statement in NLR construction to logger

src/engine/Engine.cpp
When verbosity is set to 0, _statistics in Engine.h is not updated. However, the precision restoration depends on _statistics. Therefore, we update the _statistics even if we do not print it out.
=> update the statistics object even if verbosity is 0

.travis.yml
Lcov sometimes fails with the error "cannot write to coverage.info!". The error could be caused by lcov v1.12 being installed by apt, which has been shown to have some bugs: https://stackoverflow.com/questions/37675961/error-while-code-coverage-report-using-lcov
These issues were fixed in version 1.13, so these changes update the lcov version used by travis. Also, this pr rearranges Travis a bit so that codecov runs in "after_success" only for the gcc build, and lcov is only installed for the gcc build as well. Code coverage is removed from the other build's python tests since we only need to run coverage once.
=> Use v1.13 lcov, since the default v1.12 is buggy

tools/get-openBLAS.sh
The current version of `get-openBLAS.sh` doesn't specify an output filename for `wget`. The result is that, on MacOS, the file is saved to `v0.3.9` without the `.tar.gz` extension. This causes the subsequent `tar` command to fail.
This patch changes the script to explicitly save the file as `v0.3.9.tar.gz`.
=> Fix error in get-openBLAS.

maraboupy/MarabouNetwork.py, maraboupy/MarabouUtils.py, maraboupy/test/test_equation.py
I'm not sure why the addEquality and addInequality functions are defined in MarabouUtils. It makes more sense to make them class methods, which allows a user to add equality and inequality constraints without importing MarabouUtils. The updated test file shows that the syntax is a lot more intuitive this way. 
The docstrings for these methods are slightly changed to use the Google style. A future pr will edit all of the docstrings in Maraboupy to use the Google style.
=> Move equality and inequality to MarabouNetwork

.travis.yml, maraboupy/MarabouNetwork.py, maraboupy/docs/index.rst
These changes to travis build the maraboupy documentation using the gcc compiler build. If running on the master branch (such as after merging), deploy runs to send the built html documentation to github pages.
=> Deploy Maraboupy docs to github pages

.travis.yml
The autodocumentation doesn't build correctly if the Marabou folder is not added to the PYTHONPATH environment variable. The python tests run without changing this variable because we run the tests from the root Marabou directory, but building the documentation must be done in the maraboupy/docs folder. 
This PR should fix the issue so that pages like this won't be empty: https://neuralnetworkverification.github.io/Marabou/API/0_Marabou.html
=> Add Marabou dir to pythonpath

.travis.yml
A semicolon was forgotten in #323.
=> Add semicolon

maraboupy/MarabouNetwork.py, maraboupy/test/test_nnet.py
Instead of throwing KeyError exception when given an UNSAT system, evaluateWithMarabou (and so evaluate as well) now returns None.
=> Fix evaluateWithMarabou when system is UNSAT

maraboupy/MarabouCore.cpp, maraboupy/test/test_dnc.py, src/engine/DnCManager.cpp, src/engine/DnCManager.h, src/engine/Engine.cpp, src/engine/Engine.h
Fixing issue https://github.com/NeuralNetworkVerification/Marabou/issues/330. 
The issue is that when some worker finds a SAT instance and returns a mapping from variable indices to assignments, it is using variable indices after preprocessing. This is because the worker itself does not preprocess the query but directly take in the preprocessed query, so it does not store the mapping from original variable index to the new index.
This information is stored in DnCManager._baseEngine. Therefore, we copy the tableau state of DnCManager._engineWithSATAssignment into DnCManager._baseEngine and extract solutions from the latter object, instead of the former object.
=> fix bug in dnc evaluate

src/engine/DnCManager.cpp, src/engine/DnCManager.h, src/engine/DnCMarabou.cpp, src/engine/DnCWorker.cpp, src/engine/DnCWorker.h, src/engine/tests/Test_DnCWorker.h
Change the verbosity behavior of the DnC mode:
Verbosity=0: dnc mode suppresses printing of dnc worker's progress and has the same outlook as the sequential mode.
Verbosity > 1: dnc mode prints out dnc worker's progress and never print out statistics of individual worker Engine because they are not interpretable in a parallel setting.
=> Set preprocessor's verbosity to 0 in DnC

src/engine/MaxConstraint.cpp, src/engine/tests/Test_MaxConstraint.h
Signed-off-by: tagomaru <tagomaru@users.noreply.github.com>
This PR is going to improve _addMaxConstraints_ function.
It supports only the case of _max([A, B], C])._
It supports the case of _max([A, B, C], C)_ as well.
```
// simple_model 
2,2,3,3,
2,2,3,
0,
-100000.0,-100000.0,
100000.0,100000.0,
0.0,0.0,0.0,
1.0,1.0,1.0,
1.0,1.0,
-1.0,-1.0,
0.0,
0.0,
2.0,-1.0,
-1.0,1.0,
1.0,-1.0,
0.0,
0.0,
0.0,
```
Command:
```
nnet_file_name = "./simple_model.nnet"
net = marabou.read_nnet(nnet_file_name)
net.addMaxConstraint(set(net.outputVars[0]), net.outputVars[0][0])
net.setLowerBound(net.outputVars[0][0], 2)
net.setUpperBound(net.inputVars[0][0], 1)
vals, stats = net.solve()
```
The result:
```
sat
input 0 = 1.0
input 1 = -0.0
output 0 = 2.0
output 1 = -1.0
output 2 = 1.0
```
=> improve addMaxConstratins

src/engine/SmtCore.cpp
Running "cmake --build ." causes the compiler to throw an error stating
that we should be using a reference instead of copying the "Tightening"
object. This PR just fixes the compilation error.
Marabou/src/engine/SmtCore.cpp:339:22: error: loop
variable 'bound' of type 'const Tightening' creates a copy from type 'const Tightening'
[-Werror,-Wrange-loop-analysis]
for ( const auto bound : split.getBoundTightenings() )
^
Marabou/src/engine/SmtCore.cpp:339:11: note: use
reference type 'const Tightening &' to prevent copying
for ( const auto bound : split.getBoundTightenings() )
^~~~~~~~~~~~~~~~~~
=> SmtCore.cpp compilation issue - "copy from type const Tightening"

maraboupy/Marabou.py, maraboupy/MarabouCore.cpp, maraboupy/examples/4_DncExample.py, maraboupy/test/test_dnc.py, src/engine/Engine.cpp, src/engine/SignConstraint.cpp, src/engine/SignConstraint.h, src/engine/tests/Test_SignConstraint.h
Currently for BNNs, only input splitting is supported in SnC mode. This PR extends the notion of polarity to Sign constraint, thus enabling the same branching heuristic as relu-splitting used in SnC for BNNs.
=> Polarity in sign constraint

src/common/GurobiWrapper.cpp, src/common/GurobiWrapper.h, src/configuration/GlobalConfiguration.cpp, src/configuration/GlobalConfiguration.h
Before the following command would result in an Gurobi error:
`./Marabou ../resources/nnet/acasxu/ACASXU_experimental_v2a_2_9.nnet ../resources/properties/acas_property_1.txt --milp-timeout=0.001 `
This is because getObjectiveBound is not protected when no satisfying assignment is found. This PR fixes this bug.
=> Bug fix in getting objective from Gurobi

src/engine/MILPEncoder.cpp
Signed-off-by: tagomaru <tagomaru@users.noreply.github.com>
This PR is going to fix the compile issue of MILPEncoder.cpp.
I got the below error on macOS.
```
$ cmake --build . 
[  0%] Building CXX object CMakeFiles/MarabouHelper.dir/src/engine/MILPEncoder.cpp.o
/Users/XXX/Documents/work/Marabou/src/engine/MILPEncoder.cpp:73:22: error: loop variable 'term' of type 'const Equation::Addend' creates a copy from
type 'const Equation::Addend' [-Werror,-Wrange-loop-analysis]
for ( const auto term : equation._addends )
^
/Users/XXX/Documents/work/Marabou/src/engine/MILPEncoder.cpp:73:11: note: use reference type 'const Equation::Addend &' to prevent copying
for ( const auto term : equation._addends )
^~~~~~~~~~~~~~~~~
&
1 error generated.
```
I think this problem does not happen on Ubuntu and …
=> fixing the issue of MILPEncoder

src/input_parsers/PropertyParser.cpp
The check for scalar on the right hand side throws error on scientific notations. This PR fixes that.
=> Fix in property parser

src/engine/AbsoluteValueConstraint.cpp, src/engine/AbsoluteValueConstraint.h, src/engine/PiecewiseLinearConstraint.cpp, src/engine/PiecewiseLinearConstraint.h, src/engine/ReluConstraint.cpp, src/engine/ReluConstraint.h, src/engine/SignConstraint.cpp, src/engine/SignConstraint.h, src/engine/tests/Test_ReluConstraint.h, src/engine/tests/Test_SignConstraint.h, src/nlr/Layer.cpp
This PR:
* introduces a joint PhaseStatus enumeration for all PiecewiseLinearConstraints
* refactors _phaseStatus member from derived classes into PiecewiseLinearConstraint
* refactors usage of local PhaseStatus enumerations with the global enumeration
* removes local PhaseStatus enumerations
To add new classes inheriting PiecewiseLinearConstraint their phase status elements need to be added to the PhaseStatus enumeration. Classes like Disjunction or MaxConstraint use PhaseStatus enumeration as an unsigned value instead of the label.
=> Refactor _phaseStatus from individual classes into PiecewiseLinearConstraint

maraboupy/Marabou.py, maraboupy/MarabouCore.cpp, src/configuration/OptionParser.cpp, src/configuration/Options.cpp, src/configuration/Options.h, src/engine/Engine.cpp, src/engine/Preprocessor.cpp
Currently, Preprocessor uses a default value of epsilon from GlobalConfiguration for bound tightening.
The code of this PR enables to define this epsilon's value from command line and while using maraboupy API.
=> support user defined preprocessor bound tolerance in marabou/py api

.github/workflows/ci.yml
Adds a basic Github Actions workflow for CI which runs a matrix strategy over compilers - [gcc, clang]. For each it does the following:
- Prepares build folder
- Caches tools folder and compilation artifacts between runs 
- Sets up CMake
- Runs make
- Runs system and regression tests
- Checks Python bindings
- Runs code coverage for Python API
=> Introduce CI using Github actions

.github/workflows/ci.yml, src/engine/ContextDependentPiecewiseLinearConstraint.cpp, src/engine/ContextDependentPiecewiseLinearConstraint.h, src/engine/PiecewiseLinearConstraint.h
This PR introduces an implementation of PiecewiseLinearConstraint using
context-dependent (CD) data structures from CVC4, which lazily and automatically
backtrack in sync with the central context object. These data structures
are delicate and require that data stored is safe to memcopy around. 
Members are initialized using the initializeCDOs( Context context ) method.
Subclasses need to call initializeDuplicatesCDOs() method in the
duplicateConstraint() method to avoid sharing context-dependent members.
CDOs need not be initialized for pre-processing purposes.
The class uses CDOs to record:
* _cdConstraintActive
* _cdPhaseStatus
* _cdInfeasibleCases
PhaseStatus enumeration is used to keep track of current phase of the
object, as well as to record previously explored phases. This replaces …
=> Context Dependent Piecewise Linear Constraint

CMakeLists.txt, src/engine/BoundManager.cpp, src/engine/BoundManager.h, src/engine/CMakeLists.txt, src/engine/Tableau.cpp, src/engine/Tableau.h, src/engine/tests/Test_BoundManager.h
BoundManager class is a context-dependent implementation of a centralized
variable registry and their bounds. The intent it so use a single BoundManager
object between multiple bound tightener classes, which enables
those classes to care only about bounds and forget about book-keeping. 
Furthermore, the context-dependent implementation eliminates the need for 
eager memory book-keeping.
BoundManager provides a method to obtain a new variable with:
- registerNewVariable().
The bound values and tighten flags are stored using context-dependent objects,
which backtrack automatically with the central _context object.
There are two sets of methods to set bounds:
-  setLower/UpperBounds - local methods used to update bounds
-  tightenLower/Upper Bounds - shared method to update bounds, …
=> Bound Manager Class

.github/workflows/ci.yml, src/engine/Preprocessor.cpp
This PR is going to try to fix the issue regarding installing pkg on CI which happened during CI test for #439 and #440.
=> Fix issue of installing pkg on CI

src/engine/ContextDependentPiecewiseLinearConstraint.h
Clang reports inconsistent override error in ContextDependentPiecewiseLinearConstraint.h during CI. This PR fixes the issue.
=> Fix CI - clang compilation

maraboupy/MarabouCore.cpp
it is necessary for tools like pybind11-stubgen to generate the stubs correctly, because EquationType is used in Equation::init
=> move binding of EquationType

src/engine/AbsoluteValueConstraint.cpp, src/engine/AbsoluteValueConstraint.h, src/engine/ContextDependentPiecewiseLinearConstraint.cpp, src/engine/ContextDependentPiecewiseLinearConstraint.h, src/engine/DisjunctionConstraint.cpp, src/engine/DisjunctionConstraint.h, src/engine/MaxConstraint.cpp, src/engine/MaxConstraint.h, src/engine/PiecewiseLinearConstraint.h, src/engine/ReluConstraint.cpp, src/engine/ReluConstraint.h, src/engine/SignConstraint.cpp, src/engine/SignConstraint.h, src/engine/tests/Test_AbsoluteValueConstraint.h, src/engine/tests/Test_DisjunctionConstraint.h, src/engine/tests/Test_MaxConstraint.h, src/engine/tests/Test_ReluConstraint.h, src/engine/tests/Test_SignConstraint.h
This PR introduces support  in the ContextDependentPiecewiseLinearConstraint 
class to store bounds using a BoundManager object. Like other context-dependent
members, once the BoundManager object is registered, all the bounds are stored and 
retrieved through the BoundManager.
This PR introduces methods to interface between local and global means of
storing bounds. For this purpose the following methods are introduced in
ContextDependentPiecewiseLinearConstraint class:
bool existsLowerBound( unsigned variable );
unsigned getLowerBound( unsigned variable );
void setLowerBound( unsigned variable );
bool existsUpperBound( unsigned variable );
unsigned getUpperBound( unsigned variable );
void setUpperBound( unsigned variable );
All calls to check, read or write local bound arrays are replaced …
=> Add BoundManager support to CDPWLC

src/engine/RowBoundTightener.cpp, src/engine/RowBoundTightener.h, src/engine/Tableau.cpp, src/engine/Tableau.h
This PR adds a BoundManager member to RowBoundTightener and Tableau with with get/set methods that allow smooth semantic switch between local and centralized bound management.
ConstraintBoundTightener is not updated, since it will be subsumed by a central BoundManager.
=> Add BoundManager to RowBoundTightener and Tableau

maraboupy/MarabouCore.cpp, src/common/Statistics.cpp, src/common/Statistics.h, src/engine/CDSmtCore.cpp, src/engine/CDSmtCore.h, src/engine/Engine.h, src/engine/IEngine.h, src/engine/ITableau.h, src/engine/SmtCore.cpp, src/engine/Tableau.h, src/engine/TrailEntry.h, src/engine/tests/MockEngine.h, src/engine/tests/MockTableau.h
This PR introduces a class with context-dependent implementation of the SmtCore. 
The CDSmtCore class implementation relies on:
- Access to the unique context object from which all the context-dependent structures are obtained.
- PiecewiseLinearConstraint class stores its search state in a context-dependent manner (already implemented) and 
modifying it using nextFeasibleCase()/markInfeasible() methods.
- Using BoundManager class to store bounds in a context-dependent manner (to be integrated in a future patch).
The CDSmtCore distinguishes between: **decisions** and **implications**. 
Decision is a case of PiecewiseLinearConstraint (represented using PhaseStatus enum), which is being asserted on the trail. The fact that it is a decision implies that the PiecewiseLinearConstraint has at …
=> Context-dependent SmtCore

src/engine/InputQuery.cpp, src/engine/InputQuery.h, src/engine/Preprocessor.cpp, src/engine/Preprocessor.h
During the preprocessing we make a large number of calls to the InputQuery::get{Upper,Lower}Bound() methods. On large networks this makes preprocessing slow.
This PR:
Store the variable upper-/lower- bounds as two local arrays in the Preprocessor object at the beginning of preprocessing, read/update the two arrays during preprocessing (instead of read/update the preprocessed query object). And finally store the updated bounds back to the preprocessed query after preprocessing.
=> Preprocessor refactor

tools/download_boost.sh, tools/download_openBLAS.sh
Fixing the OpenBlas installation failure on Mac following this post: https://stackoverflow.com/questions/51761599/cannot-find-stdio-h
=> export sdk path when installing OpenBLAS on Mac.

maraboupy/Marabou.py, maraboupy/MarabouCore.cpp, maraboupy/MarabouNetwork.py, maraboupy/examples/0_NNetExample.py, maraboupy/examples/1_TensorflowExample.py, maraboupy/examples/2_ONNXExample.py, maraboupy/examples/3_MarabouCoreExample.py, maraboupy/examples/4_DncExample.py, maraboupy/examples/5_DisjunctionConstraintExample.py, maraboupy/test/test_core.py, maraboupy/test/test_dnc.py, maraboupy/test/test_equation.py, maraboupy/test/test_network.py, maraboupy/test/test_query.py, maraboupy/test/test_statistics.py, src/configuration/GlobalConfiguration.cpp
1. Now the solve method of Maraboupy returns the exitcode of the Engine. Before there was no way to differ "error" and "unsat".
2. Extended the tests/examples accordingly.
3. decrease the default value of the numerical tolerance.
=> Access ExitCode from maraboupy 

src/engine/AutoTableau.h, src/engine/Engine.cpp, src/engine/Engine.h, src/engine/ITableau.h, src/engine/T/TableauFactory.h, src/engine/Tableau.cpp, src/engine/Tableau.h, src/engine/real/TableauFactory.cpp, src/engine/tests/MockTableau.h, src/engine/tests/MockTableauFactory.h, src/engine/tests/Test_Tableau.h
This PR passed a BoundManager object to the Tableau which is not used by default. 
The PR introduces  _useBoundManager flag and Tableau::enableBoundManager() 
method (for purposes of testing and integration).
=> Add BoundManager object to the Tableau

src/engine/Engine.cpp
Accidentally removed random seed setting in single-threaded mode.
=> Put back random seed setting. 

src/engine/Tableau.cpp
In Tableau::updateVariableToComplyWith*Bounds methods
=> Prevent access to Tableau internals when not in native mode

src/configuration/OptionParser.cpp, src/configuration/Options.cpp, src/configuration/Options.h, src/engine/Marabou.cpp, src/engine/Marabou.h
This PR exposes functionality to debug a solution to the command line. See --help for detailed command line arguments.
This feature is intended for developers, but can be used to report bugs by the users as well. 
The basic use case scenario: a satisfying assignment is cut off (unsoundly) during the search on the development branch. 
The user can then export the satisfying assignment using the sound version of the tool and import it into the unsound version to obtain information at which point in the search is the satisfying assignment cut off.
=> Add export/import Assignment features for debugging

src/common/Statistics.cpp, src/common/Statistics.h, src/engine/Engine.cpp, src/engine/SmtCore.cpp, src/engine/SmtCore.h
This PR adds basic statistic tracking of number of context push/pop operations, as well as time breakdown between the push/pop and related hook calls.
=> Add Statistic tracking for Context push/pop operations

maraboupy/MarabouCore.cpp, src/engine/Engine.cpp, src/engine/Engine.h
This add a way to get the current query with the current bound, allowing to return a processed query to maraboupy.
=> export preprocess query to maraboupy

src/common/GetCPUData.h
Fixes #593.
On Apple M1 machines, building Marabou fails because `cpuid.h` does not support the ARM64 architecture.
Simply not including `cpuid.h` on ARM64 architectures allows for the build to succeed.
The `getCPUId` macro definition then falls back to always yield `"#"` which should be fine, as the only place where `getCPUId` seems to be used is `DnCManager.cpp` for logging purposes (which in turn does nothing in non-DEBUG builds).
=> Do not include cpuid.h on Apple ARM64.

src/engine/DisjunctionConstraint.cpp, src/engine/InputQuery.cpp, src/nlr/DeepPolyWeightedSumElement.cpp
1. Condition for constraint being obsolete was incorrect in DisjunctionConstraint => for now DisjunctionConstraint is never obsolete
2. nlr was constructed even when there is no input variables => don't construct nlr in this case
=> fix bug in disjunction constraint

maraboupy/MarabouCore.cpp, maraboupy/test/test_disjunction.py, src/engine/DisjunctionConstraint.cpp
1. Fix encoding bug of DisjunctionConstraint in python API
2. Throw InfeasibleQueryException() when _feasibleDisjuncts becomes empty 
3. Added some unit tests
=> Fix encoding bug of disjunction in maraboupy

maraboupy/test_requirements.txt, src/input_parsers/OnnxParser.cpp, src/input_parsers/OnnxParser.h
Node names are not necessarily unique, and actually don't need to be for the parser code to work. Only input node names need to be unique
=> Fix bug in ONNX parser with network with duplicate names

maraboupy/test_requirements.txt, pyproject.toml
This PR lowers the version bound for TensorFlow, because the maraboupy tests fail for version 2.13.
See [this failing test](
https://github.com/NeuralNetworkVerification/Marabou/actions/runs/5522523078/jobs/10072235077#step:3:7592):
```
> simp_graph_def = graph_util.convert_variables_to_constants(sess,sess.graph.as_graph_def(),outputNames)
E AttributeError: module 'tensorflow.python.framework.graph_util' has no attribute 'convert_variables_to_constants'
```
=> Lower TensorFlow version bound

.github/workflows/cibuildwheel.yml
This PR sets up trusted publishing to PyPI so that new releases for x86_64 architectures are automatically pushed to PyPI when a new version tag is created.
=> Setup trusted publishing to PyPI on tag

CHANGELOG.md, maraboupy/Marabou.py, maraboupy/MarabouNetworkONNX.py, maraboupy/test/test_onnx.py
Also fix a minor bug exposed by the test.
=> Do not reindex output variables in python ONNX parser by default 

.gitattributes
Fixes https://github.com/NeuralNetworkVerification/Marabou/issues/661
=> Add .gitattributes file to stop Git from trying to display diffs of ONNX files

src/input_parsers/OnnxParser.cpp, src/input_parsers/OnnxParser.h, src/input_parsers/TensorUtils.h
Fixes the crash in https://github.com/NeuralNetworkVerification/Marabou/issues/744 but not the performance issues.
=> Fixed ill-specified int type in ONNX parsing

.pre-commit-config.yaml, README.md, tools/clang-format-src.sh
This touches up the docs and adds instructions to them on how to get `clang-format` installed as a pre-commit hook in a slightly more robust way. In particular, we use `pre-commit` to ensure there's no need for a special bash script any more, and to make it easy for everyone to ensure that formatting runs whenever they commit.
@wu-haoze if you run then everything will be setup for you.
```bash
pip install pre-commit
pre-commit install
```
=> Touch up README.md and run `clang-format` via precommit hooks

CHANGELOG.md, maraboupy/Marabou.py, maraboupy/MarabouNetworkONNX.py, maraboupy/MarabouNetworkTF.py, maraboupy/parsers/ONNXParser.py, maraboupy/test/test_onnx.py
As discussed, removes the option to reindex the output variables as it is no longer needed. It was used to test the output of these parsers against the now defunct nnet format parser.
=> Remove output variable reindexing in Python API

CMakeLists.txt
Given that we might be upgrading to a new version of C++ and thus bumping all our dependencies in the near future, this is a first step in cleaning up the `CMakeLists` file. Localises all the relevant definitions so that you don't have to go trawling through the entire file to find the relevant variables for a given dependency. This should be entirely a no-op, no new code has been added or removed.
Arguably some old code should be removed but will leave that for later.
=> Reorganise main CMakeLists file

.github/workflows/ci.yml, maraboupy/examples/0_NNetExample.py, maraboupy/examples/1_TensorflowExample.py, maraboupy/examples/2_ONNXExample.py, maraboupy/examples/4_DncExample.py, maraboupy/examples/5_DisjunctionConstraintExample.py
There are some path and index issues with the python API examples. This PR fixes them. Now all the examples terminate fine.
=> Fix python API examples

CHANGELOG.md, src/input_parsers/TensorUtils.cpp, src/input_parsers/TensorUtils.h
Fixes https://github.com/NeuralNetworkVerification/Marabou/issues/854
Sorry for the delay @idan0610. Your network should work now!
=> Fixed bug in  node in command-line ONNX parser

CMakeLists.txt, src/basis_factorization/tests/Test_SparseUnsortedArrays.h, src/basis_factorization/tests/Test_SparseUnsortedLists.h, src/input_parsers/OnnxParser.cpp, src/input_parsers/VnnLibParser.cpp, tools/download_boost.sh
The CI in various places is failing:
e.g. https://github.com/NeuralNetworkVerification/Marabou/actions/runs/12862710327/job/35858064473#step:12:122
because of a dangling reference. `AttributeProto` object may be deassigned as it is a local, so therefore better simply to return a copy of the `TensorProto` object.
=> Try to fix dangling reference flagged by CI

src/input_parsers/InputQueryBuilder.cpp, src/input_parsers/InputQueryBuilder.h
Found by LeakSanitizer. Class members were dynamically allocated but never released.
=> Fix a memory leak by introducing destructor for InputQueryBuilder
